bkcervar/Controllers/ContactSurfaceController.cs
using bkcervar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Umbraco.Core.Logging;
using Umbraco.Web.Mvc;

namespace bkcervar.Controllers
{
    public class ContactSurfaceController : SurfaceController
    {
        public ActionResult ShowForm()
        {
            ContactModel myModel = new ContactModel();
            return PartialView("ContactForm", myModel);
        }

        public ActionResult HandleFormPost(ContactModel model)
        {

            var newComment = Services.ContentService.CreateContent(model.Name + " - " + DateTime.Now.ToString("dd-MM-yyyy HH:mm"), CurrentPage.Id, "contactFormula");
            newComment.SetValue("emailFrom", model.Email);
            newComment.SetValue("contactName", model.Name);
            newComment.SetValue("contactMessage", model.Message);
            Services.ContentService.SaveAndPublishWithStatus(newComment);
            LogHelper.Debug(typeof(ContactSurfaceController),"model" + model.Email +  "name" + model.Name + " message" + model.Message);

            MailMessage mail = new MailMessage();
            //var from = new MailAddress(Email.Text);
            mail.From = new MailAddress(model.Email);
            mail.To.Add("seba7964@gmail.com");
            mail.Subject = "Konktaktirajte nas";
            mail.IsBodyHtml = false;
            mail.Body = "You just got a contact email: " + model.Email + "\n" +
                        "Name: " + model.Name + "\n"
                        + "Email: " + model.Message + "\n";

            SmtpClient smtp = new SmtpClient();

            smtp.Send(mail);

            return RedirectToCurrentUmbracoPage();


        }
    }
}

bkcervar/Views/ContactFormula.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

@{
	Layout = "Master.cshtml";
}

bkcervar/Views/ContactPage.cshtml
@using bkcervar.Controllers;
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
<div class="container-fluid">
    <div class="container" id="contact-page-container">
        
       @Html.Action("ShowForm","ContactSurface")
    </div>
</div>

bkcervar/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using bkcervar.Controllers
@{
Layout = "Master.cshtml";
}
    <link href="@Url.Content("~/css/homeStylesheet.css")" rel="stylesheet" type="text/css" />
<div>
    @{ 
        IHtmlString scrapedTable = Html.Raw("<table>" + CurrentStanding.Parse() + "</table>");
    }
</div>

<script>
    function hoverSponsor(){
        $("#myCarousel").carousel("pause");
        $("#myCarousel").attr("data-pause", "hover");
    }
    function hoverExitSponsor(){
        $("#myCarousel").carousel("cycle");
        $("#myCarousel").attr("data-pause", "false");
    }
</script>
<div id="myCarousel" class="carousel slide" data-interval="3000"  data-ride="carousel" data-pause="false">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox" style="width:100%;height:600px">




        @{
            string[] imageList = CurrentPage.pageImage.Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries);
            string addedActive = "active";
            
        }

        @foreach (string img in imageList)
        {
            var media = Umbraco.Media(img);
            <div class="item @addedActive">
                @{addedActive = "";}

                <img src="@media.umbracoFile" style="width:100%;height:600px">
            </div>
                    }
            <div class="item" id="isSponsorSlide" onmouseover="javascript:hoverSponsor();return;" onmouseleave="javascript:hoverExitSponsor();return;">
                <div style="width:100%;height:600px">
                    
                  
                    <p style="font-size:70px;text-align:center;color:red">ŽELITE LI POSTATI SPONZOR?</p>
                    <table id="sponsor-table">
                        <tr>
                    <td>
                        
                        <img class="card-img-top" src="http://sierracascadeexpo.com/application/files/8514/4572/6080/Gold_Medal_5-150x150.png" alt="Card image cap">
                        <div class="card-block">
                            <h4 class="card-title">Gold Sponzorstvo</h4>
                            <p class="card-text">-Sponzorstvo Eko Akcije, Ljetna Škola i Memorijalni turnir Lucio Pulin</p>
                            <p class="card-text">-Na sva tri eventa sponzor će biti posebno istaknut, može postaviti svoj transparent i biti će istaknut u medijima</p>
                            <script type="text/javascript">
                                function test() {


                                if ($(window).width() < 768) {
                                    document.getElementById("abc").href="http://localhost:51959/hr/sponzori/";
                                } else {
                                    document.getElementById("abc").href="http://localhost:51959/hr/contact-us/";
                                }
                                }
                            </script>
                            <a href="#" id="abc" onclick="test()" class="btn btn-primary">Saznaj Više</a> 
                        </div>
                        
                    </td>

                    <td>
                        <img class="card-img-top" src="https://www.craftspiritsxchange.com/skin/frontend/base/default/images/medals/silver.png" alt="Card image cap">
                        <div class="card-block">
                            <h4 class="card-title">Silver Sponzorstvo</h4>
                            <p class="card-text">-Sponzorstva dva eventa (po želji) te nešto najdivnije na svijetu</p>
                            <p class="card-text">-Biti će istaknut samo u onim događajima koje sponzorira, može postaviti mini logo te će biti spomenut u medijima</p>
                            <script type="text/javascript">
                                function testsilver() {


                                if ($(window).width() < 768) {
                                    document.getElementById("silver").href="http://localhost:51959/hr/sponzori/";
                                } else {
                                    document.getElementById("silver").href="http://localhost:51959/hr/contact-us/";
                                }
                                }
                            </script>
                            <a href="#" id="silver" onclick="testsilver()" class="btn btn-primary">Saznaj Više</a> 
                        </div>
                    </td>


                    <td>
                        <img class="card-img-top" src="https://rozwarner.files.wordpress.com/2011/12/bronze_medal_2.png?w=150&h=150" alt="Card image cap">
                        <div class="card-block">
                            <h4 class="card-title">Bronze Sponzorstvo</h4>
                            <p class="card-text">-Sponzorstvo jedan event (po želji) te opet nesto divno na svijetu</p>
                            <p class="card-text">-Biti će istaknut samo na popisu sponzora te će biti spomenut tijekom održavanja eventa samo učesnicima (lokalno)</p>
                            
                            <script type="text/javascript">
                                function testbronze() {


                                if ($(window).width() < 768) {
                                    document.getElementById("bronze").href="http://localhost:51959/hr/sponzori/";
                                } else {
                                    document.getElementById("bronze").href="http://localhost:51959/hr/contact-us/";
                                }
                                }
                            </script>
                           <a href="#" id="bronze" onclick="testbronze()"  class="btn btn-primary">Saznaj Više</a> 
                         
                           
                        </div>
                    </td>
                        </tr>
                        </table>

</div>
            </div>

        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>


</div>




<div class="container col-md-5 col-md-offset-2">
    <div class="container-fluid" style="margin:50px auto;">
        <div class="panel panel-default" style="background-color: rgba(0,0,0,0);border: none;word-break: break-all;">

                    <div class="container-fluid">
                   <div class="panel-header" style="background-color:white">   <h2>NAJAVE I NOVOSTI</h2>
            
                    </div>
                        </div>
                
            



                <div class="container-fluid">
                    
                    <br>
                    @{
                        var cul = Model.CurrentCulture;
                        var langCult = cul + "";
                        if (langCult.Split('-').Length != 1)
                        {
                            langCult = langCult.Split('-')[0];
                        }
                        var notElegantno = langCult == "en";
                        var elegantno = 1096;
                        if (notElegantno)
                        {
                            elegantno = 1062;
                        }
                        var newsNode = Umbraco.TypedContent(elegantno).Children.Reverse().ToList();
                        var newsCount = newsNode.Count;
                        var newsCountToShow = 3;
                    }
                    @foreach (var listItem in @newsNode)
                    {
                        if (newsCountToShow > 0)
                        {
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <a href="@listItem.Url">
                                        <h3 class="panel-title">
                                            @listItem.GetPropertyValue("pageTitle")
                                        </h3>
                                    </a>
                                </div>
                                <div class="panel-body">
                                    @Umbraco.Truncate(@listItem.GetPropertyValue("newsText").ToString(), 200)
                                </div>
                            </div>
                            newsCountToShow--;
                        }
                        else
                        {
                            break;
                        }
                    }
                </div>
            </div>
    </div>
</div>
<div class="container col-md-2" style="margin-top:105px;">
    <div id="currentStandings">
        @scrapedTable
    </div>
    </div>
@* <div class="container col-md-2 col-md-offset-5">
    <div class="container-fluid" style="margin:50px auto;">
        <div class="panel panel-default" style="background-color: rgba(0,0,0,0);border: none;word-break: break-all;">

           

            <div class="container-fluid">
                                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <a href="#">
                                            <h3 class="panel-title">
                                                HELLO
                                            </h3>
                                        </a>
                                    </div>
                                    <div class="panel-body">
                                        HELLO CONTENT
                                    </div>
                                </div>
            </div>
        </div>
    </div>
</div> *@
</div>

bkcervar/Views/Lucio.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
<div class="container col-md-8 col-md-offset-2">
    <div class="container-fluid" style="margin:50px auto;">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>@CurrentPage.pageTitle</h3>
            </div>
            <div class="panel-body">
                <img src="@CurrentPage.pageImage" alt="@CurrentPage.Name" style="max-width: 50%;float:right;margin-left:10px;margin-bottom:10px;padding:0px;" />
                <div style="word-break: break-all;align:left;">
                    @CurrentPage.bodyText
                </div>
            </div>
        </div>
    </div>
</div>

bkcervar/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="~/scripts/lightbox.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/css/lightbox.css" rel="stylesheet" />
    <link href="/css/theme.less" rel="stylesheet">
    <link href="/css/cervar-theme.less" rel="stylesheet">
    <link href="/css/cervar-bootstrap-theme.css" rel="stylesheet">
    <link href="/css/Custom.css" rel="stylesheet" />
    <title>@CurrentPage.pageTitle | @CurrentPage.siteName</title>
</head>
<body>

    <header>
        @Html.Partial("Navigation")
    </header>

    <div style="width: 100% !important;">
        @RenderBody()
    </div>
    @*
    <footer class="hidden-xs hidden-sm" style="text-align:right;position: fixed;bottom: 0px;right: 20px;">
        <p>Powered by:Infosit</p>
    </footer>
    <footer class="hidden-md hidden-lg hidden-xl" style="text-align:right; margin-right: 20px;">
        <p>Powered by:Infosit</p>
    </footer>
*@
</body>
</html>

bkcervar/Views/News.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
<div class="container col-md-8 col-md-offset-2">
    <div class="container-fluid" style="margin:50px auto;">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="col-lg-4 pull-right" style="text-align:right;">
                    <h6>Created at: @Model.Content.CreateDate.ToString("D")</h6>
                    <h6>Last edited: @Model.Content.UpdateDate.ToString("D")</h6>
                </div>
                <h2>@CurrentPage.Name</h2>
            </div>
            <div class="panel-body" id="news-panel-body">
                @CurrentPage.newsText
            </div>

        </div>
    </div>
    <div class="container-fluid">
    </div>
</div>
@{
    string[] imageList = CurrentPage.pageImage.Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries);

    var counter = 0;
}


@foreach (string img in imageList)
{
    counter++;
    if (counter < 4)
    {
        var media = Umbraco.Media(img);
        var bannerImageId = "banner-image" + counter;


        <img src="@media.umbracoFile" id="@bannerImageId"
             style="width:100%;height:50px">
    }
}

<script type="text/javascript">
    function repositionImage(){
        var screenWidth = $(window).width();
        var imageWidth = +$("#banner-image3").css("width").split("px")[0];
        if (screenWidth > 768) {
            $("#banner-image3").css("margin-left", (screenWidth-imageWidth)/2);
        } else {
            $("#banner-image1").css("margin-left", (screenWidth - imageWidth) / 2);
            $("#banner-image2").css("margin-left", (screenWidth - imageWidth) / 2);
            $("#banner-image3").css("margin-left", (screenWidth - imageWidth) / 2);
        }
    }
    repositionImage()
    $(window).resize(function () {
        repositionImage();
    })
</script>

bkcervar/Views/NewsOverview.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";

    var ListOfNews = CurrentPage.Children().OrderBy("CreateDate desc");
}
<div class="container col-md-8 col-md-offset-2">
    <div class="container-fluid " style="margin:50px auto;">

        <div class="panel panel-default" id="news-panel-panel-default">
            <div class="panel-heading">

                <h1>@CurrentPage.Name</h1>
                @CurrentPage.newsOverviewBodyText
                <div class="panel-body">

                    @foreach (var news in ListOfNews)
                    {
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <a href="@news.Url">
                                    <h3 class="panel-title">
                                        @news.Name
                                    </h3>
                                </a>
                            </div>
                            <div class="panel-body">
                                @Umbraco.Truncate(@news.newsText, 100)
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

bkcervar/Views/Search.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

    <div class="container col-md-8 col-md-offset-2">
    <div class="container-fluid" style="margin:50px auto;">
        <div class="panel panel-default">
            <div class="panel-heading">
@*
    @{

        var searchQuery = Request.QueryString["query"];

        if (!string.IsNullOrEmpty(searchQuery))
        {
            <div class="searchresults">
                <h2>Your search results for <strong>@searchQuery</strong></h2>
                <ul>
                    @foreach (var result in Umbraco.Search(searchQuery))
                    {
                        <li>
                            <a href="@result.Url">@result.Name</a>
                        </li>
                    }

                </ul>
*@  @Umbraco.RenderMacro("ezSearch")
                        </div>
               

            </div>
        </div>
    </div>
</div>

bkcervar/Views/Sponzori.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Sponzori>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<div class="container col-md-8 col-md-offset-2">
    <div class="container-fluid" style="margin:50px auto;">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>@CurrentPage.pageTitle</h3>
            </div>
            <div class="panel-body">
                
                    @CurrentPage.bodyText
                </div>
            </div>
        </div>
    </div>

bkcervar/Views/Table.cshtml
@using bkcervar.Models;
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
    <div class="container col-md-8 col-xs-12 col-sm-12 col-md-offset-2 col-sm-offset-0 col-xs-offset-0">
        <div class="container-fluid" style="margin:50px auto;">
            <div class="panel panel-default">
                <table class="table table-bordered" style="text-align:center; background:white;">


                    <thead class="thead">
                    <th style="text-align: center;">Redni broj</th>
                    <th style="text-align: center;">Ime i prezime igrača</th>
                    <th style="text-align: center;">Reg. broj</th>
                    <th style="text-align: center;">Adresa stanovanja</th>
                    </thead>

                    @{

                        PetaPoco.Database db = new PetaPoco.Database("umbracoDbDSN");


                        var sql = (PetaPoco.Sql.Builder)

                        .Append("SELECT * FROM Igraci4");


                    }

                    @foreach (var a in db.Query<Igrac4>("SELECT * FROM Igraci4"))
                    {

                    <tr>
                        <td>@a.Red_broj</td>
                        <td>@a.ImePrezime</td>
                        <td>@a.Reg_broj</td>
                        <td>@a.Adresa</td>
                    </tr>

                    }



                </table>
            </div>
        </div>
    </div>
}

bkcervar/Views/ezSearch.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}
<h2>@Umbraco.Field("pageName")</h2>
@Umbraco.RenderMacro("ezSearch")